## Top level app properties
app:
  name: ConfigurationPropertiesDemoApp
  description: ${app.name} is a spring boot app that demonstrates how to use external configuration properties
  upload-dir: /uploads
  connect-timeout: 500ms
  read-timeout: 10s
  security:
    username: admin
    password: 123456
    roles: USER,ADMIN,PARTNER   # List Property
    enabled: true
    ## Map Properties (permissions)
    permissions:
      CAN_VIEW_POSTS: true
      CAN_EDIT_POSTS: true
      CAN_DELETE_POSTS: false
      CAN_VIEW_USERS: true
      CAN_EDIT_USERS: true
      CAN_DELETE_USERS: false